site_name: RS Booking

site_name: Booking

repo_name: "2023.1 Booking"
repo_url: "https://github.com/Requisitos-de-Software/2023.1-Booking"

copyright: "Copyright &copy; 2023 rs"

theme:
  name: material
  logo: images/bookingIcon.png
  favicon: images/bookingIcon.png
  palette:
    primary: blue
    
nav:
  - Home: index.md
  - Atas: 
      - 01/04: atas/ata_01_04.md
  - Planejamento:
      - Ferramentas: planejamento/ferramentas.md
      - Cronograma planejado: planejamento/cronograma.md
      - Rich Picture: planejamento/richPicture.md