site_name: RS Booking

site_name: Booking

repo_name: "2023.1 Booking"
repo_url: "https://github.com/Requisitos-de-Software/2023.1-Booking"

copyright: "Copyright &copy; 2023 rs"

theme:
  name: material
  logo: images/bookingIcon.png
  favicon: images/bookingIcon.png
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Trocar para o modo escuro

    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Trocar para o modo claro
    
nav:
  - Home: index.md
  - Atas: 
      - 01/04/2023: atas/ata_01_04.md
      - 07/04/2023: atas/ata_07_04.md
      - 21/04/2023: atas/ata_21_04.md
      - 28/04/2023: atas/ata_28_04.md
      - 05/05/2023: atas/ata_05_05.md
  - Apresentações: 
      - Primeira Apresentação: apresentacoes/primeiraApresentacao.md
      - Segunda Apresentação: apresentacoes/segundaApresentacao.md
      - Terceira Apresentação: apresentacoes/terceiraApresentacao.md
  - Pré-Rastreabilidade:
      - Rich Picture: prePlanejamento/richPicture.md
  - Planejamento:
      - Aplicativo selecionado: planejamento/aplicativoSelecionado.md
      - Aplicativos analisados: planejamento/aplicativosAnalisados.md
      - Ferramentas: planejamento/ferramentas.md
      - Disponibilidade dos membros: planejamento/disponibilidade.md
      - Metodologia: planejamento/metodologia.md
      - Cronogramas:
        - Cronograma planejado: planejamento/cronograma.md
        - Cronograma realizado: planejamento/cronogramaRealizado.md
  - Elicitação:
      - Perfil de usuário: elicitacao/perfilDeUsuario.md
      - Personas: elicitacao/personas.md
      - Brainstorm: elicitacao/brainstorm.md
      - Observação: elicitacao/observacao.md
      - Storytelling: elicitacao/storytelling.md
  - Priorização:
      - Three Level-Scale: elicitacao/threeLevelScale.md
      - Moscow: elicitacao/moscow.md
      - In or Out: elicitacao/inOrOut.md
  - Modelagem:
      - Cenários: modelagem/cenarios.md
      - Léxicos: modelagem/lexicos.md
      - Casos de uso: modelagem/casosDeUso.md
      - Especificação Suplementar: modelagem/especificacaoSuplementar.md
      - Modelagem Ágil:
        - Backlog: modelagem/modelo-agil/backlog.md
        - Histórias de Usuário: modelagem/modelo-agil/historiasDeUsuario.md
        - NFR Framework: modelagem/modelo-agil/nfrFramework.md
  - Verificação grupo 3:
      - Metodologia: verificacao3/metodologia.md
      - Planejamento:
        - Cronograma: verificacao3/planejamento/cronograma.md
        - Lista de Aplicativos: verificacao3/planejamento/listaDeAplicativos.md 
      - Elicitação:
        - Perfil de usuário: verificacao3/elicitacao/perfilUsuario.md
        - Questionários: verificacao3/elicitacao/questionarios.md
      - Priorização:
        - Casos de uso: verificacao3/priorizacao/casoUso.md
        - In or Out: verificacao3/priorizacao/inOrOut.md
        - First Things First: verificacao3/priorizacao/firstThingsFirst.md
      - Modelagem:
        - NFR Framework: verificacao3/modelagem/nfrFramework.md
        - Especificação Suplementar: verificacao3/modelagem/especificacaoSuplementar.md
