site_name: RS Booking

site_name: Booking

repo_name: "2023.1 Booking"
repo_url: "https://github.com/Requisitos-de-Software/2023.1-Booking"

copyright: "Copyright &copy; 2023 rs"

theme:
  name: material
  logo: images/bookingIcon.png
  favicon: images/bookingIcon.png
  palette:
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Trocar para o modo escuro

    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Trocar para o modo claro
    
nav:
  - Home: index.md
  - Atas: 
      - 01/04/2023: atas/ata_01_04.md
      - 07/04/2023: atas/ata_07_04.md
      - 21/04/2023: atas/ata_21_04.md
      - 28/04/2023: atas/ata_28_04.md
  - Apresentações: 
      - Primeira Apresentação: apresentacoes/primeiraApresentacao.md
      - Segunda Apresentação: apresentacoes/segundaApresentacao.md
  - Pré-Rastreabilidade:
      - Rich Picture: prePlanejamento/richPicture.md
  - Planejamento:
      - Aplicativo selecionado: planejamento/aplicativoSelecionado.md
      - Aplicativos analisados: planejamento/aplicativosAnalisados.md
      - Ferramentas: planejamento/ferramentas.md
      - Disponibilidade dos membros: planejamento/disponibilidade.md
      - Metodologia: planejamento/metodologia.md
      - Cronograma planejado: planejamento/cronograma.md
      - Cronograma realizado: planejamento/cronogramaRealizado.md
  - Elicitação:
      - Perfil de usuário: elicitacao/perfilDeUsuario.md
      - Personas: elicitacao/personas.md
      - Brainstorm: elicitacao/brainstorm.md
      - Observação: elicitacao/observacao.md
      - Storytelling: elicitacao/storytelling.md
  - Priorização:
      - Three Level-Scale: elicitacao/threeLevelScale.md
      - Moscow: elicitacao/moscow.md
      - In or Out: elicitacao/inOrOut.md
  - Modelagem:
      - Especificação Suplementar: modelagem/especificacaoSuplementar.md
      - Casos de uso: modelagem/casosDeUso
