site_name: RS Booking

site_name: Booking

repo_name: "2023.1 Booking"
repo_url: "https://github.com/Requisitos-de-Software/2023.1-Booking"

copyright: "Copyright &copy; 2023 rs"

theme:
  name: material
  logo: images/bookingIcon.png
  favicon: images/bookingIcon.png
  palette:
    - scheme: default
      primary: blue
      accent: light blue
    
nav:
  - Home: index.md
  - Atas: 
      - 01/04/2023: atas/ata_01_04.md
      - 07/04/2023: atas/ata_07_04.md
  - Apresentações: 
      - Primeira Apresentação: apresentacoes/primeiraApresentacao.md
  - Planejamento:
      - Aplicativo selecionado: planejamento/aplicativoSelecionado.md
      - Aplicativos analisados: planejamento/aplicativosAnalisados.md
      - Ferramentas: planejamento/ferramentas.md
      - Disponibilidade dos membros: planejamento/disponibilidade.md
      - Cronograma planejado: planejamento/cronograma.md
      - Metodologia: planejamento/metodologia.md
  - Pré-Rastreabilidade:
      - Rich Picture: planejamento/richPicture.md
